#the purpose of this workflow is to deploy functions each time there is a push to the master branch
name: deploy-fb-functions

on: push 
    

jobs: #things that this workflow will do
    
    deploy-functions: 
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v3
            
            - name: install-npm-packages
              run: | 
                cd functions
                npm install
              
   
            - name: deploy-fb-functions
              uses: w9jds/firebase-action@master
              with: 
                args: deploy --only functions
              env: 
                FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}} 
            
            
            
          
    
        
